# Generated by Django 3.0.3 on 2020-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='user_budget',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='mobilenum',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ExpenseInfo',
        ),
    ]
